version: "3.6"

services:
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ${TMA_ROOT}./docker/nginx:/etc/nginx
    ports:
    - 2999:80
    depends_on:
      - front
      - back

  front:
    image: ghcr.io/samipourquoi/tma/front
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    depends_on:
      - back
    ports:
      - 3000:3000
    extra_hosts:
      - host.docker.internal:host-gateway

  back:
    image: ghcr.io/samipourquoi/tma/back
    build:
      context: .
      dockerfile: docker/back/Dockerfile
    depends_on:
      - db
    ports:
      - 3001:3001
    volumes:
      - ${TMA_ROOT}./config:/back/config
      - ${TMA_ROOT}./store:/back/store
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: library/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: tmadb
      POSTGRES_USER: tma
      POSTGRES_PASSWORD: supersecret
    ports:
      - 3002:3002
    command: -p 3002
