version: "3.8"

services:
  db:
    image: library/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: tmadb
      POSTGRES_USER: tma
      POSTGRES_PASSWORD: supersecret
    ports:
      - "3002:5432"
